import { useEffect, useRef, useState } from 'react';
import { CardText } from './CardText';
import { useAuth } from '../auth/AuthContext';
import { apiUrl } from '../config/api';
import type { CardDetail } from '../services/catalog-api';

type Entry={card:CardDetail;quantity:number;foil?:boolean;foil_token?:boolean};
type State={gold:number;booster_price:number;starter_price:number;owned:string[];packs:{id:number;art:string;opened_at:string|null}[];starters:{id:string;name:string;cover:string}[];collection:Entry[];deck:{card_id:number;quantity:number}[];foils:number[];tokens:number};
const arts=[['elsa','Elsa'],['mickey','Mickey'],['maleficent','Malévola']] as const;
const format=(n:number)=>n.toLocaleString('pt-BR');
function PackArt({art}:{art:string}){return <div className={`castle-pack-art castle-pack-art--${art}`} role="img" aria-label={`Booster de ${arts.find(a=>a[0]===art)?.[1]??art}`}/>;}
function CardArt({entry,foil=false}:{entry:Entry;foil?:boolean}){
 const modal=useRef<HTMLDialogElement>(null),card=entry.card;
 const visual=<div className={foil||entry.foil?'castle-card-art card-foil':'castle-card-art'}><img src={card.image.full||card.image.thumbnail||''} alt={card.full_name}/>{(foil||entry.foil)&&<span className="card-foil__glitter" aria-hidden="true"/>}</div>;
 return <><button type="button" className="castle-card-enlarge" aria-label={`Ampliar ${card.full_name} e ler tradução`} onClick={()=>modal.current?.showModal()}>{visual}<span>🔍 Ampliar</span></button>
 <dialog ref={modal} className="castle-card-detail" aria-label={`Detalhes de ${card.full_name}`} onCancel={e=>{e.stopPropagation();e.preventDefault();modal.current?.close();}} onClick={e=>{e.stopPropagation();if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.current?.close();}}}>
 <button type="button" className="castle-detail-close" onClick={()=>modal.current?.close()} aria-label="Fechar detalhes" autoFocus>×</button><div className="castle-detail-layout"><div>{visual}</div><section><h2>{card.pt_br.full_name||card.full_name}</h2><p>{card.color} · {card.type} · {card.rarity}{card.inkwell?' · Tinteiro':''}</p><div className="castle-detail-stats">{[['Custo',card.cost],['Força',card.strength],['Vontade',card.willpower],['Lore',card.lore]].map(([label,value])=><span key={String(label)}><small>{label}</small><b>{value??'—'}</b></span>)}</div><h3>Tradução PT-BR</h3><strong>{card.pt_br.subtypes_text}</strong><p>{card.pt_br.full_text?<CardText text={card.pt_br.full_text}/>:card.original.full_text?'Tradução ainda indisponível. Confira o original abaixo.':'Esta carta não possui texto de regras.'}</p>{card.pt_br.flavor_text&&<blockquote>{card.pt_br.flavor_text}</blockquote>}<details open={!card.pt_br.full_text&&!!card.original.full_text}><summary>Texto original em inglês</summary><strong>{card.original.full_name}</strong><p><CardText text={card.original.full_text||'This card has no rules text.'}/></p></details></section></div></dialog></>;
}

export function CastleShop({initialTab='shop',onChanged}:{initialTab?:'shop'|'deck';onChanged:()=>void}){
 const {csrfToken}=useAuth();const [data,setData]=useState<State|null>(null),[tab,setTab]=useState<'shop'|'packs'|'deck'|'edit'>(initialTab),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[quantities,setQuantities]=useState<Record<string,number>>({}),[confirm,setConfirm]=useState<{id:string;name:string;quantity:number;price:number;key:string}|null>(null),[revealed,setRevealed]=useState<Entry[]>([]),[step,setStep]=useState(-1),[animation,setAnimation]=useState(false),[openingArt,setOpeningArt]=useState('mickey'),[deck,setDeck]=useState<Record<number,number>>({}),[search,setSearch]=useState('');
 const purchaseDialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(!confirm||!purchaseDialog.current)return;const dialog=purchaseDialog.current;dialog.showModal();return()=>dialog.close();},[confirm]);
 const lock=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 async function request<T>(action='',body?:unknown):Promise<T>{const response=await fetch(apiUrl('/adventure/shop'+(action?'/'+action:'')),{credentials:'include',method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(body?{'X-CSRF-Token':csrfToken}:{})},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok||!result.success)throw Error(result.message||'Não foi possível concluir.');return result.data;}
 async function refresh(){const state=await request<State>();setData(state);setDeck(Object.fromEntries(state.deck.map(c=>[c.card_id,c.quantity])));}
 useEffect(()=>{void refresh().catch(e=>setNotice(e.message));return()=>{if(timer.current)clearTimeout(timer.current);};},[]);
 async function buy(){if(!confirm||lock.current)return;lock.current=true;setBusy(true);setNotice('');try{await request('buy',{product_id:confirm.id,quantity:confirm.quantity,request_key:confirm.key});setConfirm(null);window.dispatchEvent(new Event('wallet-updated'));onChanged();setNotice('Compra concluída. Seus itens foram salvos.');await refresh();}catch(e){setNotice(e instanceof Error?e.message:'Falha na compra.');}finally{lock.current=false;setBusy(false);}}
 async function open(pack:State['packs'][number]){if(lock.current)return;lock.current=true;setBusy(true);setNotice('');try{const result=await request<{cards:Entry[]}>('open',{pack_id:Number(pack.id)});setOpeningArt(pack.art);setRevealed(result.cards);setStep(0);const animate=!pack.opened_at&&!matchMedia('(prefers-reduced-motion: reduce)').matches;setAnimation(animate);if(animate)timer.current=setTimeout(()=>setAnimation(false),1500);onChanged();await refresh();}catch(e){setNotice(e instanceof Error?e.message:'Falha ao abrir.');}finally{lock.current=false;setBusy(false);}}
 async function saveDeck(){if(lock.current)return;lock.current=true;setBusy(true);setNotice('');try{await request('deck',{cards:Object.entries(deck).filter(([,q])=>q>0).map(([id,quantity])=>({card_id:Number(id),quantity}))});setData(current=>current?{...current,deck:Object.entries(deck).filter(([,q])=>q>0).map(([id,quantity])=>({card_id:Number(id),quantity}))}:current);setTab('deck');setNotice('Deck da aventura salvo. Seus decks do Versus não foram alterados.');onChanged();}catch(e){setNotice(e instanceof Error?e.message:'Falha ao salvar.');}finally{lock.current=false;setBusy(false);}}
 function selectProduct(id:string,name:string,quantity:number,price:number){setNotice('');setConfirm({id,name,quantity,price,key:crypto.randomUUID()});}
 function skip(){if(timer.current)clearTimeout(timer.current);setAnimation(false);setStep(revealed.length);}
 if(!data)return <p role="status">{notice||'Carregando loja do castelo…'}</p>;
 if(revealed.length)return <section className="castle-opening"><header><h2>{step>=revealed.length?'Suas novas cartas':animation?'Abrindo booster…':`Carta ${step+1} de ${revealed.length}`}</h2><p>Cartas já salvas na coleção da aventura. Fechar não perde o resultado.</p><button onClick={skip}>Pular animação · Ver todas</button></header>{animation?<div className="castle-pack-tear"><PackArt art={openingArt}/><span>✦</span></div>:step<revealed.length?<div className="castle-reveal"><CardArt entry={revealed[step]}/><h3>{revealed[step].card.full_name}</h3><p>{revealed[step].card.rarity}{revealed[step].foil?' · FOIL PERMANENTE':''}{revealed[step].foil_token?' · Repetida: +1 token foil':''}</p><button onClick={()=>setStep(s=>s+1)}>{step===revealed.length-1?'Ver todas':'Próxima carta →'}</button></div>:<><div className="castle-cards-grid">{revealed.map((e,i)=><article key={i}><CardArt entry={e}/><small>{e.card.full_name}{e.foil?' ✦ FOIL':''}{e.foil_token?' · +1 token':''}</small></article>)}</div><button onClick={()=>{setRevealed([]);setTab('packs');}}>Voltar aos meus boosters</button></>}</section>;
 const total=Object.values(deck).reduce((a,b)=>a+b,0);
 const saved=Object.fromEntries(data.deck.map(e=>[e.card_id,e.quantity]));
 const selected=data.collection.filter(e=>(deck[e.card.id]??0)>0);
 const colors=new Set(selected.flatMap(e=>e.card.colors));
 const counts:Record<string,number>={};selected.forEach(e=>{const key=e.card.original.full_name||e.card.full_name;counts[key]=(counts[key]??0)+(deck[e.card.id]??0);});
 const valid=total>=60&&colors.size<=2&&Object.values(counts).every(n=>n<=4);
 const available=data.collection.filter(e=>e.quantity>(deck[e.card.id]??0)&&e.card.full_name.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 function cancelEdit(){setDeck(saved);setSearch('');setNotice('');setTab('deck');}
 function canAdd(e:Entry){return (deck[e.card.id]??0)<e.quantity&&(counts[e.card.original.full_name||e.card.full_name]??0)<4&&new Set([...colors,...e.card.colors]).size<=2;}

 return <section className="castle-shop"><header className="castle-shop-heading"><div><small>THE FIRST CHAPTER</small><h2>{tab==='edit'?'Editar deck da aventura':tab==='deck'?'Meu deck da aventura':'Loja do castelo'}</h2></div><strong>◈ {format(data.gold)} gold</strong></header>{tab!=='edit'&&<nav className="castle-shop-tabs" aria-label="Loja e coleção">{([['shop','Loja'],['packs',`Meus boosters (${data.packs.filter(p=>!p.opened_at).length})`],['deck','Meu deck']] as const).map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setConfirm(null);}} disabled={busy}>{label}</button>)}</nav>}{notice&&<p role="status">{notice}</p>}
 {confirm&&<dialog ref={purchaseDialog} className="castle-buy-confirm" aria-label="Confirmar compra" onCancel={e=>{e.preventDefault();e.stopPropagation();if(!lock.current)setConfirm(null);}} onClick={e=>{e.stopPropagation();if(e.target===e.currentTarget&&!lock.current){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)setConfirm(null);}}}><h3>Comprar {confirm.quantity}× {confirm.name}?</h3><p>Total: <b>{format(confirm.price*confirm.quantity)} gold</b> · Saldo restante: {format(data.gold-confirm.price*confirm.quantity)}</p><button disabled={busy||data.gold<confirm.price*confirm.quantity} onClick={()=>void buy()}>{busy?'Comprando…':'Confirmar compra'}</button> <button autoFocus disabled={busy} onClick={()=>setConfirm(null)}>Cancelar</button>{notice&&<p role="status">{notice}</p>}</dialog>}
 {tab==='shop'&&<><p>12 cartas por booster: 7 comuns, 3 incomuns e 2 raras. <b>1% de chance por pacote</b> de uma das cartas vir foil. As três embalagens têm as mesmas chances.</p><div className="castle-products">{arts.map(([art,name])=>{const quantity=quantities[art]??1;return <article key={art}><PackArt art={art}/><h3>{name}</h3><small>Booster · The First Chapter</small><strong>{format(data.booster_price)} gold</strong><label>Quantidade<input type="number" min="1" max="100" step="1" value={quantity} onChange={e=>setQuantities(q=>({...q,[art]:Number(e.target.value)}))}/></label><button disabled={busy||!Number.isInteger(quantity)||quantity<1||quantity>100||data.gold<data.booster_price*quantity} onClick={()=>selectProduct('booster-'+art,name,quantity,data.booster_price)}>Comprar · {format(data.booster_price*quantity)} gold</button></article>;})}</div><h3>Expanda sua coleção com os outros starters</h3><p>Compra única. Adiciona as 60 cartas à coleção da aventura; não substitui seu deck atual e não inclui booster extra.</p><div className="castle-products">{data.starters.map(s=><article key={s.id}><img className="castle-starter-cover" src={s.cover} alt={s.name}/><h3>{s.name}</h3><strong>{format(data.starter_price)} gold</strong><button disabled={busy||data.owned.includes(s.id)||data.gold<data.starter_price} onClick={()=>selectProduct(s.id,s.name,1,data.starter_price)}>{data.owned.includes(s.id)?'✓ Já adquirido':'Comprar 60 cartas'}</button></article>)}</div></>}
 {tab==='packs'&&<><h3>Boosters fechados</h3>{!data.packs.some(p=>!p.opened_at)?<p>Você não tem boosters fechados. As cartas dos pacotes abertos estão na sua coleção, disponível em Editar deck.</p>:<div className="castle-products">{data.packs.filter(p=>!p.opened_at).map(p=><article key={p.id}><PackArt art={p.art}/><h3>Booster #{p.id}</h3><button disabled={busy} onClick={()=>void open(p)}>{p.opened_at?'Rever cartas':'Abrir booster'}</button></article>)}</div>}</>}

 {tab==='deck'&&<><div className="castle-deck-controls"><strong>{data.deck.reduce((sum,e)=>sum+e.quantity,0)} cartas no deck</strong><button onClick={()=>{setDeck(saved);setSearch('');setNotice('');setTab('edit');}}>Editar deck →</button></div><p>Este é o deck salvo para sua jornada. Cartas da coleção só aparecem ao editar.</p><div className="castle-cards-grid">{data.collection.filter(e=>(saved[e.card.id]??0)>0).map(e=><article key={e.card.id}><CardArt entry={e} foil={data.foils.includes(e.card.id)}/><small>{e.card.full_name}</small><strong>{saved[e.card.id]}× no deck</strong></article>)}</div></>}
 {tab==='edit'&&<><div className="castle-deck-controls"><strong>{total} / mínimo 60 cartas · {colors.size}/2 cores</strong><button disabled={busy||!valid} onClick={()=>void saveDeck()}>Salvar alterações</button><button disabled={busy} onClick={cancelEdit}>Cancelar e voltar</button></div><p role="status">{valid?'Deck válido. Você pode salvar.':'Complete pelo menos 60 cartas, usando até duas cores e quatro cópias por carta.'} As alterações só são aplicadas ao salvar.</p><div className="castle-editor-columns"><section><h3>No deck · {total} cartas</h3><div className="castle-cards-grid">{selected.map(e=><article key={e.card.id}><CardArt entry={e} foil={data.foils.includes(e.card.id)}/><small>{e.card.full_name}</small><strong>{deck[e.card.id]}×</strong><button disabled={busy} onClick={()=>setDeck(d=>({...d,[e.card.id]:d[e.card.id]-1}))}>− Retirar</button></article>)}</div></section><section><h3>Coleção disponível</h3><p>Cartas dos boosters e starters adquiridos. Retirar do deck devolve a cópia para esta lista.</p><label>Buscar carta<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome da carta…"/></label><div className="castle-cards-grid">{available.map(e=><article key={e.card.id}><CardArt entry={e} foil={data.foils.includes(e.card.id)}/><small>{e.card.full_name}</small><small>{e.card.color} · {e.quantity-(deck[e.card.id]??0)} disponíveis</small><button disabled={busy||!canAdd(e)} title={!canAdd(e)?'Limite de quatro cópias ou de duas cores atingido':undefined} onClick={()=>setDeck(d=>({...d,[e.card.id]:(d[e.card.id]??0)+1}))}>+ Adicionar</button></article>)}</div>{!available.length&&<p>Nenhuma carta disponível para este filtro.</p>}</section></div></>}
 </section>;
}
