import { useEffect, useState } from 'react';
import { request } from './Shop';
import { RewardCheck, RewardCollected } from './RewardCollected';
type Mission={progress?:number;claimed?:boolean;id:string;name:string;description:string;goal:number;xp:number;gold?:number};
export function MissionIcon(){return <svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><rect x="7" y="5" width="20" height="25" rx="4" fill="#173948" stroke="#f2cc7c" strokeWidth="1.5"/><rect x="12" y="2" width="10" height="6" rx="2" fill="#e7be64"/><path d="m10 14 2 2 4-4m-6 10 2 2 4-4M19 14h4m-4 8h4" stroke="#9ff5d7" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>;}
export function DailyMissions(){
 const [missions,setMissions]=useState<Mission[]|null>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;request<{missions:Mission[]}>('/missions').then(r=>{if(active)setMissions(r.missions);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 return <section className="daily-missions"><p className="missions-notice">Login e três batalhas da aventura concedem XP automaticamente. As missões do Versus ainda aguardam integração.</p>{error?<p role="alert">{error}</p>:!missions?<p role="status">Carregando missões…</p>:<><div className="mission-list">{missions.map((m,i)=><article className={`mission-item ${m.id==='all'?'mission-item--bonus':''} ${m.claimed?'is-collected':''}`} key={m.id}><span className="mission-number">{m.claimed?<RewardCheck/>:i+1}</span><div className="mission-copy"><h3>{m.name}</h3><p>{m.description}</p><small>Meta: {m.goal} {m.id==='login'?'login':m.id==='all'?'missões':'partida(s)'} · {m.progress!==undefined?`${m.progress}/${m.goal}`:'Progresso indisponível'}</small></div><div className="mission-prize"><b>+{m.xp.toLocaleString('pt-BR')} XP</b>{m.gold!==undefined&&<small>+{m.gold.toLocaleString('pt-BR')} gold*</small>}<span>{m.claimed?<RewardCollected/>:m.progress!==undefined?'Em andamento':'Em preparação'}</span></div></article>)}</div><p className="missions-footnote">Recompensas lidas do Controle de XP e Gold. *Bônus em gold por completar todas as missões ainda sujeito à confirmação. Estes prêmios somam às recompensas das partidas.</p></>}</section>;
}
