CREATE TABLE IF NOT EXISTS economy_settings (
 setting_key VARCHAR(64) NOT NULL PRIMARY KEY,
 setting_value INT UNSIGNED NOT NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
